services:
  db:
    image: postgres
    container_name: deals_db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=moussi@25
      - POSTGRES_DB=deals_db

  web:
    container_name: deals_container
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/deals_db?createDatabaseIfNotExists=true
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=moussi@25
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  deals-assignment:
