spring:
  application:
    name: deal-analyzer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/deals_db?createDatabaseIfNotExist=true
    username: postgres
    password: moussi@25
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true